# Overall settings for PR integration via codecov.com
# See https://docs.codecov.com/docs/codecovyml-reference

# Separate PR statuses for project-level and patch-level coverage
# See https://docs.codecov.com/docs/commit-status
coverage:
    status:
        # Project-level coverage
        project:
            default:
                base: auto
                # Disable once code base is more mature.
                informational: true
                only_pulls: true
                target: auto
                threshold: 10%

        # Patch-level coverage (how well is the PR tested)
        patch:
            default:
                base: auto
                # Disable once code base is more mature.
                informational: true
                only_pulls: true
                target: auto
                threshold: 50%

# Pull request comments
# See https://docs.codecov.com/docs/pull-request-comments
comment: false

# See https://docs.codecov.com/docs/ignoring-paths
ignore:
    - 'media-experiments.php'
    - 'inc/class-blurhash.php'
    - 'inc/default-filters.php'
    - '**/*.svg'
    - 'packages/edit-post/src/preferencesModal/preference-base-option'
    - 'packages/edit-post/src/preferencesModal/preferences-modal'
    - 'packages/edit-post/src/preferencesModal/preferences-modal-section'
    - 'packages/edit-post/src/preferencesModal/preferences-modal-tabs'
    - 'packages/edit-post/src/preferencesModal/tabs'
